import type {
  Product,
  Category,
  SiteSettings,
  SiteReview,
  Coupon,
  ShippingZoneConfig,
  Order,
} from '../types/ecommerce';

export const FALLBACK_CATEGORIES: Category[] = [
  {
    id: 'cat-1',
    name: 'Mustard Oil',
    banglaName: 'কাঠের ঘানির সরিষার তেল',
    slug: 'mustard-oil',
    image: '/images/barakah/sorisa5liter.png',
    itemCount: 4,
    description: 'সনাতন কাঠের ঘানিতে কোনো প্রকার কৃত্রিম তাপ বা কেমিক্যাল ছাড়া খাঁটি মাঘী সরিষা থেকে ভাঙানো তেল।',
    isActive: true,
    displayOrder: 1,
  },
  {
    id: 'cat-2',
    name: 'Organic Honey',
    banglaName: 'সুন্দরবনের খাঁটি মধু',
    slug: 'honey',
    image: '/images/barakah/honey.png',
    itemCount: 2,
    description: 'সুন্দরবনের গভীর অরণ্যের মৌচাক থেকে সংগ্রহকৃত অপরিশোধিত প্রাকৃতিক মধু।',
    isActive: true,
    displayOrder: 2,
  },
  {
    id: 'cat-3',
    name: 'Ghee & Dairy',
    banglaName: 'খাঁটি গাওয়া ঘি',
    slug: 'ghee',
    image: '/images/barakah/ghee.png',
    itemCount: 2,
    description: 'দেশি গাভীর খাঁটি দুধের মাখন থেকে তৈরি সুগন্ধি দানাদার গাওয়া ঘি।',
    isActive: true,
    displayOrder: 3,
  },
  {
    id: 'cat-4',
    name: 'Dry Leaves & Powders',
    banglaName: 'ভেষজ পাতা ও সুপারফুড',
    slug: 'leaves-powders',
    image: '/images/barakah/patpata.png',
    itemCount: 3,
    description: 'প্রাকৃতিক সাজনা পাতা ও পাট পাতা পরিষ্কার ও স্বাস্থ্যসম্মতভাবে রোদে শুকিয়ে প্রস্তুতকৃত।',
    isActive: true,
    displayOrder: 4,
  },
  {
    id: 'cat-5',
    name: 'Dates & Dry Fruits',
    banglaName: 'প্রাকৃতিক খেজুর ও বাদাম',
    slug: 'dates-nuts',
    image: '/images/barakah/product_one_oil.png',
    itemCount: 2,
    description: 'আমদানিকৃত প্রিমিয়াম গ্রেডের মদিনার আজওয়া খেজুর ও ড্রাই ফ্রুটস।',
    isActive: true,
    displayOrder: 5,
  },
  {
    id: 'cat-6',
    name: 'Spices & Seeds',
    banglaName: 'খাঁটি মসলা ও বীজ',
    slug: 'spices-seeds',
    image: '/images/barakah/sorisa1liter.png',
    itemCount: 2,
    description: 'কেমিক্যাল ও কৃত্রিম রঙ ছাড়া শতভাগ খাঁটি মসলা ও পুষ্টিকর চিয়া সিড।',
    isActive: true,
    displayOrder: 6,
  },
];

export const FALLBACK_PRODUCTS: Product[] = [
  {
    id: 1,
    name: 'Wood-Pressed Mustard Oil (5 Liter)',
    banglaName: 'কাঠের ঘানির খাঁটি সরিষার তেল (৫ লিটার)',
    slug: 'wood-pressed-mustard-oil-5l',
    category: 'Mustard Oil',
    categorySlug: 'mustard-oil',
    brand: 'Barakah Agro',
    sku: 'BA-MO-5000',
    price: 1350,
    oldPrice: 1550,
    stock: 45,
    image: '/images/barakah/sorisa5liter.png',
    gallery: ['/images/barakah/sorisa5liter.png', '/images/barakah/sorisa1liter.png'],
    shortDescription: 'কাঠের ঘানিতে কোল্ড-প্রেসড প্রক্রিয়ায় প্রস্তুত শতভাগ খাঁটি ও ঝাঁঝালো সরিষার তেল।',
    description:
      'বারাকাহ এগ্রোর কাঠের ঘানির খাঁটি সরিষার তেল কোনো প্রকার তাপ বা কেমিক্যাল প্রয়োগ না করে প্রাচীন সনাতন পদ্ধতিতে কোল্ড-প্রেসড করে তৈরি করা হয়। মাঘী সরিষা থেকে প্রস্তুত হওয়ায় এর ঝাঁঝ ও প্রাকৃতিক পুষ্টিগুণ যেমন ওমেগা-৩, ওমেগা-৬ এবং ভিটামিন-ই সম্পূর্ণ অক্ষত থাকে। হৃদরোগ প্রতিরোধ এবং দৈনন্দিন সুস্বাদু রান্নার জন্য এটি অতুলনীয়।',
    ingredients: '১০০% দেশি মাঘী সরিষা দানা (Cold Pressed Mustard Seeds)',
    benefits: [
      'কাঠের ঘানির সনাতন কোল্ড প্রেসড পদ্ধতি',
      'প্রাকৃতিক ঝাঁঝ ও অতুলনীয় সুবাস',
      'ক্ষতিকর কোলেস্টেরল কমায় ও হার্ট ভালো রাখে',
      'কোনো প্রকার ভেজাল, ঝাঁঝ কেমিক্যাল বা পাম তেল মুক্ত',
    ],
    rating: 4.9,
    reviewCount: 38,
    badges: ['BEST SELLING', 'OFFER'],
    isFeatured: true,
    isOffer: true,
    packages: [
      { id: 'mo-5l', label: '৫ লিটার বোতল', price: 1350, oldPrice: 1550, discount: '৳২০০ ছাড়', stock: 45 },
      { id: 'mo-2l', label: '২ লিটার বোতল', price: 580, oldPrice: 650, discount: '৳৭০ ছাড়', stock: 30 },
      { id: 'mo-1l', label: '১ লিটার বোতল', price: 290, oldPrice: 320, discount: '৳৩০ ছাড়', stock: 60 },
    ],
    createdAt: '2026-01-15T00:00:00Z',
    isActive: true,
  },
  {
    id: 2,
    name: 'Sundarban Raw Natural Honey (1 kg)',
    banglaName: 'সুন্দরবনের খাঁটি বুনো মধু (১ কেজি)',
    slug: 'sundarban-raw-honey-1kg',
    category: 'Organic Honey',
    categorySlug: 'honey',
    brand: 'Barakah Agro',
    sku: 'BA-HN-1000',
    price: 950,
    oldPrice: 1100,
    stock: 28,
    image: '/images/barakah/honey.png',
    gallery: ['/images/barakah/honey.png'],
    shortDescription: 'সুন্দরবনের গভীর অরণ্য থেকে সরাসরি সংগৃহীত ১০০% কাঁচা প্রাকৃতিক মধু।',
    description:
      'সুন্দরবনের প্রাকৃতিকভাবে গড়ে ওঠা বুনো মৌচাক থেকে ঐতিহ্যবাহী পেশাদার মৌয়ালদের সহযোগিতায় এই মধু সংগ্রহ করা হয়। এটি শতভাগ আনফিল্টার্ড এবং আনপাস্তুরিত, ফলে প্রাকৃতিক এনজাইম, পরাগ (Pollen) ও অ্যান্টিঅক্সিডেন্ট পুরোপুরি অক্ষুণ্ণ থাকে। রোগ প্রতিরোধ ক্ষমতা বৃদ্ধি এবং ঠাণ্ডা-কাশি নিরাময়ে অত্যন্ত কার্যকর।',
    ingredients: 'সুন্দরবনের প্রাকৃতিক বহুফুলের বুনো মধু (100% Raw Wild Honey)',
    benefits: [
      'রোগ প্রতিরোধ ক্ষমতা (Immunity) বৃদ্ধি করে',
      'কাশির উপশমে অত্যন্ত কার্যকর ও প্রাকৃতিক অ্যান্টিবায়োটিক',
      'চিনির স্বাস্থ্যকর প্রাকৃতিক বিকল্প',
      'প্রাকৃতিক অ্যান্টিঅক্সিডেন্ট ও এনজাইম সমৃদ্ধ',
    ],
    rating: 4.9,
    reviewCount: 42,
    badges: ['BEST SELLING'],
    isFeatured: true,
    packages: [
      { id: 'hn-1k', label: '১ কেজি কাঁচের বয়াম', price: 950, oldPrice: 1100, discount: '৳১৫০ ছাড়', stock: 28 },
      { id: 'hn-500g', label: '৫০০ গ্রাম বয়াম', price: 500, oldPrice: 580, discount: '৳৮০ ছাড়', stock: 35 },
    ],
    createdAt: '2026-01-18T00:00:00Z',
    isActive: true,
  },
  {
    id: 3,
    name: 'Pure Deshi Cow Ghee (500g)',
    banglaName: 'খাঁটি দেশি গাওয়া ঘি (৫০০ গ্রাম)',
    slug: 'pure-deshi-cow-ghee-500g',
    category: 'Ghee & Dairy',
    categorySlug: 'ghee',
    brand: 'Barakah Agro',
    sku: 'BA-GH-0500',
    price: 850,
    oldPrice: 950,
    stock: 20,
    image: '/images/barakah/ghee.png',
    gallery: ['/images/barakah/ghee.png'],
    shortDescription: 'দেশি গাভীর দুধের খাঁটি মাখন থেকে তৈরি ঐতিহ্যবাহী দানাদার গাওয়া ঘি।',
    description:
      'গ্রামের চারণভূমিতে ঘাস খাওয়া দেশি গাভীর খাঁটি দুধ সংগ্রহ করে প্রচলিত বিলো পদ্ধতিতে মাখন তোলা হয় এবং অল্প তাপে খাঁটি গাওয়া ঘি তৈরি করা হয়। এর সোনালী বর্ণ, প্রাকৃতিক দানাদার গঠন এবং মন মাতানো সুবাস যেকোনো খাবারকে করে তোলে অত্যন্ত তৃপ্তিদায়ক।',
    ingredients: '১০০% দেশি গাভীর দুধের মাখন (Clarified Butter)',
    benefits: [
      'ঐতিহ্যবাহী দানাদার গঠন ও খাঁটি সুঘ্রাণ',
      'হজমশক্তি বৃদ্ধি ও শারীরিক দুর্বলতা দূর করে',
      'মস্তিষ্ক ও চোখের দৃষ্টিশক্তি ভালো রাখে',
      'কোনো কৃত্রিম ফ্লেভার বা রাসায়নিক প্রিজারভেটিভ নেই',
    ],
    rating: 5.0,
    reviewCount: 31,
    badges: ['BEST SELLING'],
    isFeatured: true,
    packages: [
      { id: 'gh-500', label: '৫০০ গ্রাম বয়াম', price: 850, oldPrice: 950, discount: '৳১০০ ছাড়', stock: 20 },
      { id: 'gh-1k', label: '১ কেজি বয়াম', price: 1650, oldPrice: 1850, discount: '৳২০০ ছাড়', stock: 15 },
    ],
    createdAt: '2026-01-20T00:00:00Z',
    isActive: true,
  },
  {
    id: 4,
    name: 'Sun-Dried Sajna Leaves (100g)',
    banglaName: 'প্রাকৃতিক শুকনো সাজনা পাতা (১০০ গ্রাম)',
    slug: 'sun-dried-sajna-leaves',
    category: 'Dry Leaves & Powders',
    categorySlug: 'leaves-powders',
    brand: 'Barakah Agro',
    sku: 'BA-SJ-0100',
    price: 180,
    oldPrice: 220,
    stock: 50,
    image: '/images/barakah/sajna.png',
    gallery: ['/images/barakah/sajna.png'],
    shortDescription: 'পুষ্টির আধার সাজনা পাতা স্বাস্থ্যসম্মত উপায়ে রোদে শুকিয়ে প্রস্তুত।',
    description:
      'সাজনা পাতা বিশ্বজুড়ে সুপারফুড হিসেবে পরিচিত। এতে দুধের চেয়ে বেশি ক্যালসিয়াম, কলার চেয়ে বেশি পটাশিয়াম এবং কমলার চেয়ে বহুগুণ ভিটামিন-সি রয়েছে। বারাকাহ এগ্রোর শুকনো সাজনা পাতা সম্পূর্ণ ধুলোবালি মুক্ত পরিচ্ছন্ন পরিবেশে রোদে শুকানো হয়। এটি চা আকারে অথবা ভাতের সাথে মিশিয়ে সহজেই গ্রহণ করা যায়।',
    ingredients: '১০০% বাছাইকৃত তাজা সাজনা পাতা (Dried Moringa Oleifera Leaves)',
    benefits: [
      'উচ্চ রক্তচাপ ও ডায়াবেটিস নিয়ন্ত্রণে সহায়ক',
      'শরীরের দুর্বলতা দূর করে ও শক্তি যোগায়',
      'প্রচুর পরিমাণে ক্যালসিয়াম, আয়রন ও ভিটামিন এ, সি সমৃদ্ধ',
      'শতভাগ প্রাকৃতিক ও অর্গানিক',
    ],
    rating: 4.8,
    reviewCount: 24,
    badges: ['BEST SELLING'],
    isFeatured: true,
    packages: [
      { id: 'sj-100', label: '১০০ গ্রাম প্যাকেট', price: 180, oldPrice: 220, discount: '৳৪০ ছাড়', stock: 50 },
      { id: 'sj-250', label: '২৫০ গ্রাম প্যাকেট', price: 420, oldPrice: 500, discount: '৳৮০ ছাড়', stock: 35 },
    ],
    createdAt: '2026-01-22T00:00:00Z',
    isActive: true,
  },
  {
    id: 5,
    name: 'Sun-Dried Pat Pata (Jute Leaves 100g)',
    banglaName: 'প্রাকৃতিক শুকনো পাট পাতা (১০০ গ্রাম)',
    slug: 'sun-dried-pat-pata',
    category: 'Dry Leaves & Powders',
    categorySlug: 'leaves-powders',
    brand: 'Barakah Agro',
    sku: 'BA-PP-0100',
    price: 160,
    oldPrice: 190,
    stock: 60,
    image: '/images/barakah/patpata.png',
    gallery: ['/images/barakah/patpata.png'],
    shortDescription: 'ঐতিহ্যবাহী স্বাদ ও পুষ্টিতে ভরপুর স্বাস্থ্যসম্মত শুকনো পাট পাতা।',
    description:
      'পাট পাতা বাঙালি সংস্কৃতির একটি চিরচেনা পুষ্টিকর শাক। মৌসুম শেষেও যাতে এর পুষ্টি এবং সুস্বাদু স্বাদ উপভোগ করা যায়, সেজন্য সতেজ দেশি পাট পাতা বাছাই করে পরিচ্ছন্নভাবে শুকানো হয়েছে। এটি গরম ভাতের সাথে ঝোলে অথবা হালকা তেলে ভেজে মচমচে করে খাওয়ার জন্য অসাধারণ।',
    ingredients: '১০০% দেশি কচি পাট পাতা (Dried Jute Leaves)',
    benefits: [
      'হজমশক্তি বৃদ্ধি ও পেটের সুস্থতায় সহায়ক',
      'প্রচুর ডায়েটারি ফাইবার ও পুষ্টি উপাদান সমৃদ্ধ',
      'চোখের স্বাস্থ্য ও ত্বকের উজ্জ্বলতা বাড়াতে সাহায্য করে',
      'দীর্ঘদিন সংরক্ষণযোগ্য স্বাস্থ্যসম্মত প্যাকেজিং',
    ],
    rating: 4.7,
    reviewCount: 19,
    badges: ['TRENDING'],
    isFeatured: true,
    packages: [
      { id: 'pp-100', label: '১০০ গ্রাম প্যাকেট', price: 160, oldPrice: 190, discount: '৳৩০ ছাড়', stock: 60 },
      { id: 'pp-250', label: '২৫০ গ্রাম প্যাকেট', price: 380, oldPrice: 450, discount: '৳৭০ ছাড়', stock: 40 },
    ],
    createdAt: '2026-01-25T00:00:00Z',
    isActive: true,
  },
  {
    id: 6,
    name: 'Premium Madina Ajwa Dates (500g)',
    banglaName: 'মদিনার প্রিমিয়াম আজওয়া খেজুর (৫০০ গ্রাম)',
    slug: 'madina-ajwa-dates-500g',
    category: 'Dates & Dry Fruits',
    categorySlug: 'dates-nuts',
    brand: 'Barakah Agro',
    sku: 'BA-DT-0500',
    price: 680,
    oldPrice: 780,
    stock: 25,
    image: '/images/barakah/sorisa1liter.png',
    gallery: ['/images/barakah/sorisa1liter.png'],
    shortDescription: 'মদিনা শরিফ থেকে সরাসরি আমদানিকৃত নরম ও সুস্বাদু খাঁটি আজওয়া খেজুর।',
    description:
      'আজওয়া খেজুর নবীজির (সা.) অত্যন্ত প্রিয় এবং হাদিস অনুযায়ী বিশেষ বরকতময় ফল। এটি হৃদযন্ত্রের সুস্থতা এবং শরীরকে টক্সিনমুক্ত রাখতে বিশেষভাবে পরিচিত। বারাকাহ এগ্রো আপনাদের দিচ্ছে মদিনা থেকে সরাসরি সংগৃহীত এ গ্রেডের খাঁটি আজওয়া খেজুর।',
    ingredients: '১০০% অরিজিনাল সৌদি আজওয়া খেজুর (Original Ajwa Dates)',
    benefits: [
      'হাদিস বর্ণিত বরকতময় ও পুষ্টিকর ফল',
      'হৃদরোগের ঝুঁকি কমাতে সহায়তা করে',
      'প্রাকৃতিক শক্তি ও আয়রনের চমৎকার উৎস',
    ],
    rating: 4.9,
    reviewCount: 27,
    badges: ['NEW ARRIVAL'],
    isFeatured: true,
    packages: [
      { id: 'dt-500', label: '৫০০ গ্রাম বক্স', price: 680, oldPrice: 780, discount: '৳১০০ ছাড়', stock: 25 },
      { id: 'dt-1k', label: '১ কেজি বক্স', price: 1300, oldPrice: 1500, discount: '৳২০০ ছাড়', stock: 18 },
    ],
    createdAt: '2026-02-01T00:00:00Z',
    isActive: true,
  },
  {
    id: 7,
    name: 'Organic Chia Seeds (250g)',
    banglaName: 'অর্গানিক চিয়া সিড (২৫০ গ্রাম)',
    slug: 'organic-chia-seeds-250g',
    category: 'Spices & Seeds',
    categorySlug: 'spices-seeds',
    brand: 'Barakah Agro',
    sku: 'BA-CS-0250',
    price: 240,
    oldPrice: 290,
    stock: 35,
    image: '/images/barakah/patpata.png',
    gallery: ['/images/barakah/patpata.png'],
    shortDescription: 'ওমেগা-৩ ও ডায়েটারি ফাইবার সমৃদ্ধ প্রিমিয়াম কোয়ালিটি চিয়া সিডস।',
    description:
      'চিয়া সিড শরীরের ওজন নিয়ন্ত্রণ, কোলেস্টেরল হ্রাস এবং দীর্ঘ সময় শক্তি ধরে রাখার জন্য বিশ্বব্যাপী প্রশংসিত। এটি পানিতে ভিজিয়ে লেবুর শরবত, সালাদ বা ওটমিলের সাথে সহজে গ্রহণ করা যায়।',
    ingredients: '১০০% ন্যাচারাল চিয়া বীজ (Whole Raw Chia Seeds)',
    benefits: [
      'ওজন নিয়ন্ত্রণ ও দীর্ঘস্থায়ী এনার্জি বজায় রাখে',
      'প্রচুর ওমেগা-৩ ফ্যাটি এসিড ও ফাইবার সমৃদ্ধ',
      'হাড় মজবুত করে এবং মেটাবলিজম উন্নত করে',
    ],
    rating: 4.8,
    reviewCount: 16,
    badges: ['NEW ARRIVAL'],
    isFeatured: false,
    packages: [
      { id: 'cs-250', label: '২৫০ গ্রাম জিপলক প্যাক', price: 240, oldPrice: 290, discount: '৳৫০ ছাড়', stock: 35 },
      { id: 'cs-500', label: '৫০০ গ্রাম প্যাক', price: 450, oldPrice: 550, discount: '৳১০০ ছাড়', stock: 25 },
    ],
    createdAt: '2026-02-05T00:00:00Z',
    isActive: true,
  },
  {
    id: 8,
    name: 'Wood-Pressed Mustard Oil (1 Liter)',
    banglaName: 'কাঠের ঘানির খাঁটি সরিষার তেল (১ লিটার)',
    slug: 'wood-pressed-mustard-oil-1l',
    category: 'Mustard Oil',
    categorySlug: 'mustard-oil',
    brand: 'Barakah Agro',
    sku: 'BA-MO-1000',
    price: 290,
    oldPrice: 320,
    stock: 60,
    image: '/images/barakah/sorisa1liter.png',
    gallery: ['/images/barakah/sorisa1liter.png'],
    shortDescription: 'কাঠের ঘানির আসল ঝাঁঝালো তেল প্রতিদিনের সুস্বাদু ও পুষ্টিকর রান্নায়।',
    description:
      '১ লিটার পারিবারিক বোতলে কাঠের ঘানিতে কোল্ড-প্রেসড সরিষার তেল। খাঁটি সরিষার আসল ঘ্রাণ ও ঝাঁঝের জন্য সেরা পছন্দ।',
    ingredients: '১০০% দেশি মাঘী সরিষা দানা',
    benefits: [
      'আসল কাঠের ঘানি কোল্ড প্রেসড',
      'ঝাঁঝালো ও শতভাগ খাঁটি',
      'হৃদরোগের ঝুঁকি কমায়',
    ],
    rating: 4.9,
    reviewCount: 52,
    badges: ['BEST SELLING'],
    isFeatured: true,
    packages: [
      { id: 'mo1-1l', label: '১ লিটার বোতল', price: 290, oldPrice: 320, discount: '৳৩০ ছাড়', stock: 60 },
    ],
    createdAt: '2026-02-08T00:00:00Z',
    isActive: true,
  },
];

export const FALLBACK_REVIEWS: SiteReview[] = [
  {
    id: 'rev-1',
    author: 'মোহাম্মদ রফিকুল ইসলাম',
    city: 'মিরপুর, ঢাকা',
    rating: 5,
    comment:
      'বারাকাহ এগ্রোর কাঠের ঘানির সরিষার তেল আসলেই অতুলনীয়। তেলের আসল ঝাঁঝ এবং ভর্তা রান্নার সুবাস অসাধারণ। আমি নিয়মিত কাস্টমার হয়ে গেছি!',
    date: '৩ দিন আগে',
    productName: 'কাঠের ঘানির খাঁটি সরিষার তেল',
    image: '/images/barakah/customer1.png',
    verified: true,
  },
  {
    id: 'rev-2',
    author: 'ফারহানা আহমেদ',
    city: 'ধানমন্ডি, ঢাকা',
    rating: 5,
    comment:
      'সুন্দরবনের খাঁটি মধু ও সাজনা পাতা অর্ডার করেছিলাম। দুই দিনের মধ্যে ঢাকাতে ক্যাশ অন ডেলিভারি পেয়েছি। মধুর স্বাদ শতভাগ প্রাকৃতিক। ধন্যবাদ বারাকাহ এগ্রো!',
    date: '১ সপ্তাহ আগে',
    productName: 'সুন্দরবনের খাঁটি বুনো মধু',
    image: '/images/barakah/customer2.png',
    verified: true,
  },
  {
    id: 'rev-3',
    author: 'আরিফুল হক',
    city: 'উত্তরা, ঢাকা',
    rating: 5,
    comment:
      'দেশি গাওয়া ঘির ঘ্রাণ পুরো ঘরকে মোহিত করে। বাচ্চাদের জন্য এমন খাঁটি খাবার পেয়ে অনেক নিশ্চিন্ত বোধ করছি। সততার সাথে কাজ চালিয়ে যান।',
    date: '২ সপ্তাহ আগে',
    productName: 'খাঁটি দেশি গাওয়া ঘি',
    image: '/images/barakah/customer3.png',
    verified: true,
  },
];

export const FALLBACK_SETTINGS: SiteSettings = {
  storeName: 'Barakah Agro',
  banglaStoreName: 'বারাকাহ এগ্রো',
  tagline: 'Pure Food, Healthy Life',
  banglaTagline: 'বিশুদ্ধ খাবার, সুস্থ জীবনের জন্য',
  announcementText: '🔥 বিশেষ অফার: ২,০০০ টাকার অর্ডারে সমগ্র বাংলাদেশে হোম ডেলিভারি একদম ফ্রি!',
  hotline: '01786-239185',
  whatsappNumber: '8801786239185',
  email: 'contact@barakahagro.com',
  address: 'House 14, Road 7, Sector 3, Uttara, Dhaka-1230, Bangladesh',
  logo: '/images/barakah/logo.jpeg',
  heroHeadline: 'বিশুদ্ধ খাবার, সুস্থ জীবনের প্রতিশ্রুতি',
  heroSubheadline:
    'কাঠের ঘানিতে ভাঙ্গা খাঁটি সরিষার তেল, সুন্দরবনের প্রাকৃতিক মধু ও পুষ্টিকর সুপারফুড সরাসরি আপনার ঘরে।',
  heroImage: '/images/generated/hero_agro_farm_1790250221055.jpg',
  facebookUrl: 'https://facebook.com',
  instagramUrl: 'https://instagram.com',
  freeShippingThreshold: 2000,
  insideDhakaFee: 80,
  outsideDhakaFee: 130,
};

export const FALLBACK_COUPONS: Coupon[] = [
  {
    id: 'c1',
    code: 'BARAKAH10',
    discountType: 'percentage',
    discountValue: 10,
    minSpend: 1000,
    expiryDate: '2027-12-31',
    usageLimit: 500,
    usageCount: 42,
    isActive: true,
  },
  {
    id: 'c2',
    code: 'PURE100',
    discountType: 'fixed',
    discountValue: 100,
    minSpend: 1500,
    expiryDate: '2027-12-31',
    usageLimit: 300,
    usageCount: 18,
    isActive: true,
  },
];

export const FALLBACK_SHIPPING: ShippingZoneConfig = {
  insideDhakaFee: 80,
  outsideDhakaFee: 130,
  freeShippingThreshold: 2000,
  estimatedInsideDays: '১-২ দিন',
  estimatedOutsideDays: '২-৩ দিন',
};
