import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import type {
  Product,
  Category,
  Order,
  Coupon,
  ShippingZoneConfig,
  CustomerUser,
  SiteReview,
  SiteSettings,
} from '../src/types/ecommerce';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const DATA_DIR = path.resolve(__dirname, '../server-data');
const DB_FILE = path.join(DATA_DIR, 'db.json');

export interface DatabaseSchema {
  products: Product[];
  categories: Category[];
  orders: Order[];
  coupons: Coupon[];
  shipping: ShippingZoneConfig;
  customers: CustomerUser[];
  reviews: SiteReview[];
  settings: SiteSettings;
}

const initialSeed: DatabaseSchema = {
  settings: {
    storeName: 'Barakah Agro',
    banglaStoreName: 'বারাকাহ এগ্রো',
    tagline: 'Pure Food, Healthy Life',
    banglaTagline: 'বিশুদ্ধ খাবার, সুস্থ জীবনের জন্য',
    logo: '/images/barakah/logo.jpeg',
    hotline: '01786-239185',
    whatsappNumber: '8801786239185',
    email: 'contact@barakahagro.com',
    address: 'House 14, Road 7, Sector 3, Uttara, Dhaka-1230, Bangladesh',
    announcementText: '🚚 সমগ্র বাংলাদেশে ক্যাশ অন ডেলিভারি | ২০০০ টাকার কেনাকাটায় ফ্রি হোম ডেলিভারি | হটলাইন: ০১৭৮৬-২৩৯১৮৫',
    heroHeadline: 'বিশুদ্ধ খাবার, সুস্থ জীবনের প্রতিশ্রুতি',
    heroSubheadline: 'কাঠের ঘানিতে ভাঙ্গা খাঁটি সরিষার তেল and পুষ্টিকর সুপারফুড সরাসরি আপনার ঘরে।',
    heroImage: '/images/generated/hero_agro_farm_1790250221055.jpg',
    facebookUrl: 'https://facebook.com/barakahagro',
    instagramUrl: 'https://instagram.com/barakahagro',
    freeShippingThreshold: 2000,
    insideDhakaFee: 80,
    outsideDhakaFee: 130,
  },
  shipping: {
    insideDhakaFee: 80,
    outsideDhakaFee: 130,
    freeShippingThreshold: 2000,
    estimatedInsideDays: '২৪ - ৪৮ ঘণ্টা',
    estimatedOutsideDays: '২ - ৩ দিন',
  },
  categories: [
    {
      id: 'cat-1',
      name: 'Mustard Oil',
      banglaName: 'সরিষার তেল',
      slug: 'mustard-oil',
      description: 'কাঠের ঘানিতে কোল্ড-প্রেসড ১০০% নির্ভেজাল খাঁটি সরিষার তেল',
      image: '/images/barakah/sorisa5liter.png',
      itemCount: 2,
      isActive: true,
      displayOrder: 1,
    },
    {
      id: 'cat-2',
      name: 'Leaves & Powders',
      banglaName: 'পাতা ও ভেষজ গুঁড়া',
      slug: 'leaves-powders',
      description: 'প্রাকৃতিক পুষ্টিগুণ সমৃদ্ধ শুকনো সাজনা পাতা ও পাট পাতা',
      image: '/images/barakah/sajna-pata.jpeg',
      itemCount: 2,
      isActive: true,
      displayOrder: 2,
    },
    {
      id: 'cat-3',
      name: 'Raw Honey',
      banglaName: 'প্রাকৃতিক মধু',
      slug: 'raw-honey',
      description: 'সুন্দরবনের গভীর অরণ্যের চাক থেকে সংগৃহীত কাঁচা ও খাঁটি মধু',
      image: '/images/generated/sundarban_honey_1790250234941.jpg',
      itemCount: 2,
      isActive: true,
      displayOrder: 3,
    },
    {
      id: 'cat-4',
      name: 'Pure Ghee',
      banglaName: 'খাঁটি গাওয়া ঘি',
      slug: 'pure-ghee',
      description: 'গ্রামের দেশি গাভীর দুধ থেকে সনাতন বিলোনা পদ্ধতিতে প্রস্তুত সুগন্ধি ঘি',
      image: '/images/generated/deshi_cow_ghee_1790250246367.jpg',
      itemCount: 1,
      isActive: true,
      displayOrder: 4,
    },
    {
      id: 'cat-5',
      name: 'Dates & Dry Fruits',
      banglaName: 'খেজুর ও ড্রাই ফ্রুটস',
      slug: 'dates-dry-fruits',
      description: 'মদিনার বাছাইকৃত রাজকীয় আজওয়া খেজুর এবং প্রিমিয়াম নাটস',
      image: '/images/generated/organic_dates_nuts_1790250258013.jpg',
      itemCount: 2,
      isActive: true,
      displayOrder: 5,
    },
    {
      id: 'cat-6',
      name: 'Seeds & Superfoods',
      banglaName: 'বীজ ও সুপারফুড',
      slug: 'seeds-superfoods',
      description: 'চিয়া সিড ও পুষ্টিকর খাদ্য উপাদান',
      image: '/images/barakah/patpataupdate.jpeg',
      itemCount: 2,
      isActive: true,
      displayOrder: 6,
    },
    {
      id: 'cat-7',
      name: 'Pure Spices',
      banglaName: 'খাঁটি মসলা',
      slug: 'pure-spices',
      description: 'কেমিক্যাল ও কৃত্রিম রঙ মুক্ত হাতে তৈরি খাঁটি হলুদ ও মরিচ গুঁড়া',
      image: '/images/barakah/product_one_oil.png',
      itemCount: 2,
      isActive: true,
      displayOrder: 7,
    },
  ],
  products: [
    {
      id: 1,
      name: 'Pure Wood-Pressed Mustard Oil',
      banglaName: 'কাঠের ঘানিতে ভাঙ্গা খাঁটি সরিষার তেল',
      slug: 'pure-wood-pressed-mustard-oil',
      category: 'Mustard Oil',
      categorySlug: 'mustard-oil',
      brand: 'Barakah Agro',
      sku: 'BA-OIL-01',
      price: 260,
      oldPrice: 290,
      costPrice: 200,
      discountPercentage: 10,
      stock: 65,
      image: '/images/barakah/sorisa5liter.png',
      gallery: [
        '/images/barakah/sorisa5liter.png',
        '/images/barakah/product_one_oil.png',
      ],
      packages: [
        { id: 'p1', label: '১ লিটার', price: 260, oldPrice: 290, discount: 'Save ৳30', stock: 25 },
        { id: 'p2', label: '২ লিটার', price: 520, oldPrice: 570, discount: 'Save ৳50', stock: 15 },
        { id: 'p3', label: '৩ লিটার', price: 780, oldPrice: 850, discount: 'Save ৳70', stock: 10 },
        { id: 'p4', label: '৪ লিটার', price: 1040, oldPrice: 1140, discount: 'Save ৳100', stock: 8 },
        { id: 'p5', label: '৫ লিটার', price: 1300, oldPrice: 1450, discount: 'Save ৳150', stock: 7 },
      ],
      shortDescription: 'কাঠের ঘানিতে সনাতন পদ্ধতিতে ভাঙ্গা ১০০% বিশুদ্ধ, তীব্র ঝাঁঝালো সরিষার তেল।',
      description:
        'বারাকাহ এগ্রো সরিষার তেল সম্পূর্ণ দেশি মাঘী সরিষা থেকে কাঠের ঘানিতে ঠাণ্ডা চাপে নিষ্কাশিত। এতে কোনো প্রকার প্রিজারভেটিভ, আর্টিফিশিয়াল রঙ বা পাম অয়েল মিশ্রিত নেই। কাঠের ঘানির তেল গরম না হওয়ায় এর প্রাকৃতিক অ্যান্টিঅক্সিডেন্ট, ওমেগা-৩ ও ওমেগা-৬ ফ্যাটি অ্যাসিড সম্পূর্ণ অক্ষুণ্ণ থাকে।',
      benefits: [
        'হৃদযন্ত্রের সুস্থতা বজায় রাখে ও রক্ত সঞ্চালন উন্নত করে',
        'উচ্চ অ্যান্টি-ব্যাকটেরিয়াল ও অ্যান্টি-ফাঙ্গাল উপাদান সমৃদ্ধ',
        'ঠান্ডা-কাশি ও বুক-ব্যথায় গরম ভাতের সাথে অনন্য পথ্য',
        'ত্বক ও চুলের পুষ্টি জোগায় এবং শরীর মালিশে চমৎকার',
      ],
      ingredients: '১০০% বাছাইকৃত দেশি সরিষার বীজ (Wood Pressed First Cold Pressed)',
      weightUnit: 'Litre',
      rating: 4.9,
      reviewCount: 42,
      badges: ['BEST SELLING', 'OFFER'],
      isFeatured: true,
      isOffer: true,
      isActive: true,
      createdAt: '2026-01-10T10:00:00Z',
    },
    {
      id: 2,
      name: 'Organic Dried Sajna (Moringa) Leaf Powder',
      banglaName: 'শুকনো সাজনা পাতা / অর্গানিক মোরিঙ্গা গুঁড়া',
      slug: 'organic-dried-sajna-moringa-leaf',
      category: 'Leaves & Powders',
      categorySlug: 'leaves-powders',
      brand: 'Barakah Agro',
      sku: 'BA-SAJ-02',
      price: 375,
      oldPrice: 420,
      costPrice: 240,
      discountPercentage: 11,
      stock: 48,
      image: '/images/barakah/sajna-pata.jpeg',
      gallery: ['/images/barakah/sajna-pata.jpeg'],
      packages: [
        { id: 's1', label: '২৫০ গ্রাম', oldPrice: 375, price: 375, stock: 20 },
        { id: 's2', label: '৫০০ গ্রাম', oldPrice: 750, price: 620, discount: 'Save ৳130', stock: 18 },
        { id: 's3', label: '১ কেজি', oldPrice: 1500, price: 1150, discount: 'Save ৳350', stock: 10 },
      ],
      shortDescription: 'প্রকৃতির মিরাকল ট্রি সাজনার কচি পাতা ছায়ায় শুকিয়ে প্রস্তুত করা শতভাগ পুষ্টিকর খাদ্য।',
      description:
        'সাজনা পাতা বিশ্বের অন্যতম সেরা সুপারফুড হিসেবে স্বীকৃত। বারাকাহ এগ্রোর শুকনো সাজনা পাতা কোনো ক্ষতিকর কীটনাশক ছাড়া উৎপাদিত গাছ থেকে সাবধানে সংগ্রহ করে ছায়ায় স্বাস্থ্যসম্মত উপায়ে শুকানো হয়েছে। এতে দুধের চেয়ে বেশি ক্যালসিয়াম এবং কমলার চেয়ে বেশি ভিটামিন-সি বিদ্যমান।',
      benefits: [
        'শরীরে রোগ প্রতিরোধ ক্ষমতা (Immunity) নাটকীয়ভাবে বৃদ্ধি করে',
        'উচ্চ রক্তচাপ এবং ডায়াবেটিস নিয়ন্ত্রণে অত্যন্ত উপকারী',
        'হজমরস নিঃসরণ বাড়ায় এবং পেটের সমস্যা দূর করে',
        'ত্বকে বয়সের ছাপ দূর করে এবং প্রাকৃতিকভাবে শক্তি জোগায়',
      ],
      ingredients: '১০০% বিশুদ্ধ শুকনা সাজনা পাতা (Moringa Oleifera Leaves)',
      weightUnit: 'Gram',
      rating: 4.8,
      reviewCount: 29,
      badges: ['BEST SELLING', 'TRENDING'],
      isFeatured: true,
      isOffer: true,
      isActive: true,
      createdAt: '2026-01-12T10:00:00Z',
    },
    {
      id: 3,
      name: 'Organic Dried Jute Leaf (Pat Pata)',
      banglaName: 'শুকনো পাট পাতা গুঁড়া',
      slug: 'organic-dried-jute-leaf-pat-pata',
      category: 'Leaves & Powders',
      categorySlug: 'leaves-powders',
      brand: 'Barakah Agro',
      sku: 'BA-PAT-03',
      price: 300,
      oldPrice: 350,
      costPrice: 180,
      discountPercentage: 14,
      stock: 35,
      image: '/images/barakah/patpataupdate.jpeg',
      gallery: ['/images/barakah/patpataupdate.jpeg'],
      packages: [
        { id: 'j1', label: '২৫০ গ্রাম', oldPrice: 300, price: 300, stock: 15 },
        { id: 'j2', label: '৫০০ গ্রাম', oldPrice: 600, price: 570, discount: 'Save ৳30', stock: 12 },
        { id: 'j3', label: '১ কেজি', oldPrice: 1200, price: 1080, discount: 'Save ৳120', stock: 8 },
      ],
      shortDescription: 'ঐতিহ্যবাহী তিতা পাট পাতার শুকনা রূপ, যা রক্ত পরিশোধন ও পেটের সুস্থতায় দারুণ কার্যকরী।',
      description:
        'পাট শাকের ভেষজ গুণাবলি বাঙালি সংস্কৃতিতে চিরন্তন। বারাকাহ এগ্রোর শুকনো পাট পাতা সারা বছর খাওয়ার উপযোগী করে স্বাস্থ্যসম্মত উপায়ে প্রস্তুত। এটি স্যুপ, ঝোল বা হালকা গুঁড়ো করে ভাতের সাথে খাওয়া যায়।',
      benefits: [
        'লিভারের কার্যকারিতা বাড়ায় ও প্রাকৃতিকভাবে শরীর ডিটক্সিফাই করে',
        'রক্তস্বল্পতা দূর করে এবং উচ্চ আয়রন সমৃদ্ধ',
        'কোষ্ঠকাঠিন্য নিরাময়ে সাহায্য করে',
        'ক্ষুধা মন্দা দূর করে এবং মুখের রুচি ফেরায়',
      ],
      ingredients: 'প্রাকৃতিকভাবে শুকানো তিতা পাট পাতা (Corchorus Leaves)',
      weightUnit: 'Gram',
      rating: 4.7,
      reviewCount: 18,
      badges: ['OFFER'],
      isFeatured: true,
      isOffer: true,
      isActive: true,
      createdAt: '2026-01-15T10:00:00Z',
    },
    {
      id: 4,
      name: 'Sundarban Raw Wild Honey',
      banglaName: 'সুন্দরবনের প্রাকৃতিক চাকের মধু',
      slug: 'sundarban-raw-wild-honey',
      category: 'Raw Honey',
      categorySlug: 'raw-honey',
      brand: 'Barakah Agro',
      sku: 'BA-HNY-04',
      price: 650,
      oldPrice: 720,
      costPrice: 450,
      discountPercentage: 10,
      stock: 40,
      image: '/images/generated/sundarban_honey_1790250234941.jpg',
      gallery: ['/images/generated/sundarban_honey_1790250234941.jpg'],
      packages: [
        { id: 'h1', label: '৫০০ গ্রাম', price: 650, oldPrice: 720, discount: 'Save ৳70', stock: 25 },
        { id: 'h2', label: '১ কেজি', price: 1250, oldPrice: 1390, discount: 'Save ৳140', stock: 15 },
      ],
      shortDescription: 'সুন্দরবনের গভীর খলিসা ও গরান ফুলের খাঁটি বুনো মধু। কোনো চিনি বা হিট প্রসেসিং ছাড়া।',
      description:
        'সুন্দরবনের ঐতিহ্যবাহী মৌয়ালদের মাধ্যমে সংগৃহীত সরাসরি চাকের অপরিশোধিত কাঁচা মধু। এই মধুতে প্রাকৃতিক পোলেন, এনজাইম এবং মিনারেলস সম্পূর্ণ অক্ষত থাকে। হালকা পাতলা ঘনত্ব ও সুন্দরবনের বুনো ফুলের মোহনীয় সুবাস এর বিশুদ্ধতার প্রমাণ।',
      benefits: [
        'দ্রুত শারীরিক শক্তি বৃদ্ধি ও ক্লান্তি দূর করে',
        'কাশির প্রকোপ কমায় ও শ্বাসতন্ত্র পরিষ্কার রাখে',
        'হজম শক্তি বৃদ্ধি করে ও মেটাবলিজম চাঙ্গা রাখে',
      ],
      ingredients: '১০০% প্রাকৃতিক সুন্দরবনের ফুলের মধু (Raw Unprocessed Honey)',
      weightUnit: 'Gram',
      rating: 5.0,
      reviewCount: 56,
      badges: ['BEST SELLING', 'TRENDING'],
      isFeatured: true,
      isOffer: true,
      isActive: true,
      createdAt: '2026-01-18T10:00:00Z',
    },
    {
      id: 5,
      name: 'Traditional Deshi Cow Gawa Ghee',
      banglaName: 'খাঁটি গাওয়া ঘি (ঘরোয়া মাখন থেকে প্রস্তুত)',
      slug: 'traditional-deshi-cow-gawa-ghee',
      category: 'Pure Ghee',
      categorySlug: 'pure-ghee',
      brand: 'Barakah Agro',
      sku: 'BA-GHE-05',
      price: 750,
      oldPrice: 850,
      costPrice: 550,
      discountPercentage: 12,
      stock: 30,
      image: '/images/generated/deshi_cow_ghee_1790250246367.jpg',
      gallery: ['/images/generated/deshi_cow_ghee_1790250246367.jpg'],
      packages: [
        { id: 'g1', label: '৪০০ গ্রাম', price: 750, oldPrice: 850, discount: 'Save ৳100', stock: 18 },
        { id: 'g2', label: '৯০০ গ্রাম', price: 1550, oldPrice: 1750, discount: 'Save ৳200', stock: 12 },
      ],
      shortDescription: 'দানাযুক্ত খাঁটি দেশি গাভীর দুধের মাখন জ্বালিয়ে প্রস্তুতকৃত ঘ্রাণসমৃদ্ধ আসল গাওয়া ঘি।',
      description:
        'উত্তরবঙ্গের দেশি গাভীর তাজা দুধের ক্রিম ও দই থেকে বিলোনা পদ্ধতিতে প্রস্তুত হয় বারাকাহ এগ্রো গাওয়া ঘি। এর সোনালী বর্ণ, চমৎকার দানাদার টেক্সচার এবং মন মাতানো সুবাস যেকোনো খাবারকে অতুলনীয় করে তোলে।',
      benefits: [
        'হজম সহায়ক স্বাস্থ্যকর চর্বি (Butyric Acid) সমৃদ্ধ',
        'মস্তিষ্কের শক্তি ও স্মৃতিশক্তি বাড়াতে সহায়ক',
        'ভিটামিন এ, ডি, ই এবং কে এর সর্বোত্তম উৎস',
      ],
      ingredients: '১০০% খাঁটি দেশি গাভীর দুধের মাখন (Deshi Cow Clarified Butter)',
      weightUnit: 'Gram',
      rating: 4.9,
      reviewCount: 38,
      badges: ['BEST SELLING'],
      isFeatured: true,
      isOffer: false,
      isActive: true,
      createdAt: '2026-01-20T10:00:00Z',
    },
    {
      id: 6,
      name: 'Royal Saudi Ajwa Dates (Premium Quality)',
      banglaName: 'মদিনার রাজকীয় প্রিমিয়াম আজওয়া খেজুর',
      slug: 'royal-saudi-ajwa-dates',
      category: 'Dates & Dry Fruits',
      categorySlug: 'dates-dry-fruits',
      brand: 'Barakah Agro',
      sku: 'BA-DAT-06',
      price: 680,
      oldPrice: 750,
      costPrice: 480,
      discountPercentage: 9,
      stock: 50,
      image: '/images/generated/organic_dates_nuts_1790250258013.jpg',
      gallery: ['/images/generated/organic_dates_nuts_1790250258013.jpg'],
      packages: [
        { id: 'd1', label: '৫০০ গ্রাম', price: 680, oldPrice: 750, discount: 'Save ৳70', stock: 30 },
        { id: 'd2', label: '১ কেজি', price: 1300, oldPrice: 1450, discount: 'Save ৳150', stock: 20 },
      ],
      shortDescription: 'সরাসরি সৌদি আরবের মদিনা শরিফ থেকে আমদানিকৃত নরম, পুষ্টিকর ও মিষ্টি আজওয়া খেজুর।',
      description:
        'সুন্নতি ও সর্বোত্তম গুণসম্পন্ন আজওয়া খেজুর সরাসরি মদিনা থেকে বাছাই করে এয়ার টাইট স্বাস্থ্যসম্মত প্যাকেজিংয়ে আপনার জন্য নিয়ে এসেছে বারাকাহ এগ্রো। নরম, রসাল ও উচ্চ খনিজগুণ সমৃদ্ধ।',
      benefits: [
        'হৃদপিণ্ডের সুস্থতা রক্ষা করে ও স্ট্রোকের ঝুঁকি কমায়',
        'প্রচুর পরিমাণে প্রাকৃতিক শর্করা, আয়রন ও পটাশিয়াম সমৃদ্ধ',
        'গর্ভবতী মায়েদের জন্য অত্যন্ত উপকারী',
      ],
      ingredients: '১০০% অরিজিনাল সৌদি আজওয়া খেজুর (Grade A)',
      weightUnit: 'Gram',
      rating: 5.0,
      reviewCount: 64,
      badges: ['TRENDING', 'NEW ARRIVAL'],
      isFeatured: true,
      isOffer: true,
      isActive: true,
      createdAt: '2026-01-22T10:00:00Z',
    },
    {
      id: 7,
      name: 'Organic Black Chia Seeds',
      banglaName: 'প্রিমিয়াম অর্গানিক কালো চিয়া সিড',
      slug: 'organic-black-chia-seeds',
      category: 'Seeds & Superfoods',
      categorySlug: 'seeds-superfoods',
      brand: 'Barakah Agro',
      sku: 'BA-CHIA-07',
      price: 320,
      oldPrice: 380,
      costPrice: 200,
      discountPercentage: 15,
      stock: 55,
      image: '/images/barakah/patpataupdate.jpeg',
      gallery: ['/images/barakah/patpataupdate.jpeg'],
      packages: [
        { id: 'c1', label: '২৫০ গ্রাম', price: 320, oldPrice: 380, discount: 'Save ৳60', stock: 35 },
        { id: 'c2', label: '৫০০ গ্রাম', price: 580, oldPrice: 680, discount: 'Save ৳100', stock: 20 },
      ],
      shortDescription: 'ওমেগা-৩ ও ডায়েটারি ফাইবার সমৃদ্ধ ওজন নিয়ন্ত্রণ ও এনার্জির সেরা সুপারফুড।',
      description:
        'বারাকাহ এগ্রোর প্রিমিয়াম অর্গানিক চিয়া সিড ধুলোবালি ও ময়লামুক্ত শতভাগ বিশুদ্ধ বীজ। সকালে বা বিকেলে লেবু পানি বা টক দইয়ের সাথে প্রতিদিন ১-২ চামচ চিয়া সিড শরীরকে দীর্ঘক্ষণ হাইড্রেটেড ও চাঙ্গা রাখে।',
      benefits: [
        'ওজন কমাতে ও অতিরিক্ত ক্ষুধা নিয়ন্ত্রণে অপ্রতিদ্বন্দ্বী',
        'স্যালমন মাছের চেয়েও বেশি ওমেগা-৩ ফ্যাটি এসিড সমৃদ্ধ',
        'হাড়ের ঘনত্ব ও জয়েন্টের স্বাস্থ্য মজবুত রাখে',
      ],
      ingredients: '১০০% প্রাকৃতিক কালো চিয়া সিড (Salvia Hispanica)',
      weightUnit: 'Gram',
      rating: 4.8,
      reviewCount: 22,
      badges: ['NEW ARRIVAL'],
      isFeatured: false,
      isOffer: false,
      isActive: true,
      createdAt: '2026-02-01T10:00:00Z',
    },
    {
      id: 8,
      name: 'Pure Deshi Turmeric Powder',
      banglaName: 'খাঁটি পাহাড়ি হলুদ গুঁড়া (কেমিক্যালমুক্ত)',
      slug: 'pure-deshi-turmeric-powder',
      category: 'Pure Spices',
      categorySlug: 'pure-spices',
      brand: 'Barakah Agro',
      sku: 'BA-SPC-08',
      price: 160,
      oldPrice: 190,
      costPrice: 90,
      discountPercentage: 15,
      stock: 70,
      image: '/images/barakah/product_one_oil.png',
      gallery: ['/images/barakah/product_one_oil.png'],
      packages: [
        { id: 't1', label: '২০০ গ্রাম', price: 160, oldPrice: 190, discount: 'Save ৳30', stock: 40 },
        { id: 't2', label: '৫০০ গ্রাম', price: 380, oldPrice: 450, discount: 'Save ৳70', stock: 30 },
      ],
      shortDescription: 'কোনোরকম ভেজাল ছাড়া রোদে শুকিয়ে চূর্ণ করা পাহাড়ি জাতের উজ্জ্বল হলুদ গুঁড়া।',
      description:
        'বাজারের ভেজাল ও ক্ষতিকর লেড ক্রোমেট রঙ মুক্ত পাহাড়ি গোটা হলুদ নিজ তত্ত্বাবধানে ভাঙিয়ে তৈরি। কারকিউমিন সমৃদ্ধ এই হলুদ তরকারিতে দেবে আসল সোনালী রঙ ও খাঁটি ঝাঁঝ।',
      benefits: [
        'প্রাকৃতিক অ্যান্টিসেপটিক ও রোগ প্রতিরোধক গুণসম্পন্ন',
        'শরীরের প্রদাহ ও জয়েন্টের ব্যথা দূর করে',
      ],
      ingredients: '১০০% রোদে শুকানো পাহাড়ি হলুদ গোটা',
      weightUnit: 'Gram',
      rating: 4.9,
      reviewCount: 31,
      badges: ['OFFER'],
      isFeatured: false,
      isOffer: true,
      isActive: true,
      createdAt: '2026-02-05T10:00:00Z',
    },
  ],
  orders: [
    {
      id: 'BA-2026-000101',
      customerName: 'তানভীর আহমেদ',
      phone: '01712345678',
      email: 'tanveer@gmail.com',
      division: 'Dhaka',
      district: 'Dhaka',
      upazila: 'Mirpur',
      address: 'House 42, Road 9, Mirpur 10, Dhaka',
      deliveryLocation: 'inside',
      deliveryInstructions: 'বিকেল ৪টার পর কল দিয়ে ডেলিভারি করবেন।',
      items: [
        {
          productId: 1,
          name: 'কাঠের ঘানিতে ভাঙ্গা খাঁটি সরিষার তেল',
          packageLabel: '৫ লিটার',
          price: 1300,
          quantity: 1,
          image: '/images/barakah/sorisa5liter.png',
        },
        {
          productId: 4,
          name: 'সুন্দরবনের প্রাকৃতিক চাকের মধু',
          packageLabel: '৫০০ গ্রাম',
          price: 650,
          quantity: 1,
          image: '/images/generated/sundarban_honey_1790250234941.jpg',
        },
      ],
      subtotal: 1950,
      discount: 0,
      shippingFee: 80,
      total: 2030,
      paymentMethod: 'cod',
      paymentStatus: 'Pending',
      status: 'Delivered',
      statusHistory: [
        { status: 'Pending', timestamp: '2026-09-21T09:30:00Z', note: 'Order placed by customer' },
        { status: 'Confirmed', timestamp: '2026-09-21T10:15:00Z', note: 'Customer confirmed via phone call' },
        { status: 'Processing', timestamp: '2026-09-21T11:00:00Z', note: 'Packaging started' },
        { status: 'Packed', timestamp: '2026-09-21T14:30:00Z', note: 'Parcel handed over to Steadfast courier' },
        { status: 'Shipped', timestamp: '2026-09-22T08:00:00Z', note: 'In transit to Mirpur hub' },
        { status: 'Out for Delivery', timestamp: '2026-09-22T12:00:00Z', note: 'Delivery rider is on the way' },
        { status: 'Delivered', timestamp: '2026-09-22T16:20:00Z', note: 'Delivered successfully and payment collected' },
      ],
      adminNotes: 'Regular trusted customer. Highly satisfied with mustard oil.',
      createdAt: '2026-09-21T09:30:00Z',
      updatedAt: '2026-09-22T16:20:00Z',
    },
    {
      id: 'BA-2026-000102',
      customerName: 'মাহমুদুল হাসান',
      phone: '01898765432',
      email: 'mahmud@yahoo.com',
      division: 'Chittagong',
      district: 'Chittagong',
      upazila: 'Panchlaish',
      address: 'Flat 4B, Green Villa, Nasirabad Housing, Chittagong',
      deliveryLocation: 'outside',
      items: [
        {
          productId: 2,
          name: 'শুকনো সাজনা পাতা / অর্গানিক মোরিঙ্গা গুঁড়া',
          packageLabel: '৫০০ গ্রাম',
          price: 620,
          quantity: 2,
          image: '/images/barakah/sajna-pata.jpeg',
        },
      ],
      subtotal: 1240,
      discount: 124,
      couponCode: 'BARAKAH10',
      shippingFee: 130,
      total: 1246,
      paymentMethod: 'bkash',
      paymentStatus: 'Paid',
      transactionId: 'BK92837194A',
      status: 'Shipped',
      statusHistory: [
        { status: 'Pending', timestamp: '2026-09-23T11:00:00Z', note: 'Order placed via bKash payment' },
        { status: 'Confirmed', timestamp: '2026-09-23T11:30:00Z', note: 'Payment verified' },
        { status: 'Processing', timestamp: '2026-09-23T14:00:00Z', note: 'Order processed in central depot' },
        { status: 'Packed', timestamp: '2026-09-23T18:00:00Z', note: 'Packed with bubble wrap' },
        { status: 'Shipped', timestamp: '2026-09-24T06:30:00Z', note: 'Dispatched via Paperfly Courier' },
      ],
      adminNotes: 'Call before dispatch.',
      createdAt: '2026-09-23T11:00:00Z',
      updatedAt: '2026-09-24T06:30:00Z',
    },
    {
      id: 'BA-2026-000103',
      customerName: 'সালমা জাহান',
      phone: '01799887766',
      email: 'salma.jahan@gmail.com',
      division: 'Dhaka',
      district: 'Dhaka',
      upazila: 'Uttara',
      address: 'Sector 4, Road 11, House 29, Uttara, Dhaka',
      deliveryLocation: 'inside',
      items: [
        {
          productId: 5,
          name: 'খাঁটি গাওয়া ঘি (ঘরোয়া মাখন থেকে প্রস্তুত)',
          packageLabel: '৯০০ গ্রাম',
          price: 1550,
          quantity: 1,
          image: '/images/generated/deshi_cow_ghee_1790250246367.jpg',
        },
        {
          productId: 6,
          name: 'মদিনার রাজকীয় প্রিমিয়াম আজওয়া খেজুর',
          packageLabel: '৫০০ গ্রাম',
          price: 680,
          quantity: 1,
          image: '/images/generated/organic_dates_nuts_1790250258013.jpg',
        },
      ],
      subtotal: 2230,
      discount: 0,
      shippingFee: 0, // Free shipping over 2000!
      total: 2230,
      paymentMethod: 'cod',
      paymentStatus: 'Pending',
      status: 'Confirmed',
      statusHistory: [
        { status: 'Pending', timestamp: '2026-09-24T02:15:00Z', note: 'Order received' },
        { status: 'Confirmed', timestamp: '2026-09-24T03:40:00Z', note: 'Phone confirmed by sales team' },
      ],
      adminNotes: 'Free shipping applied (Subtotal > 2000 BDT)',
      createdAt: '2026-09-24T02:15:00Z',
      updatedAt: '2026-09-24T03:40:00Z',
    },
  ],
  coupons: [
    {
      id: 'c-1',
      code: 'BARAKAH10',
      discountType: 'percentage',
      discountValue: 10,
      minSpend: 500,
      maxDiscount: 300,
      expiryDate: '2027-12-31',
      usageLimit: 1000,
      usageCount: 42,
      isActive: true,
    },
    {
      id: 'c-2',
      code: 'WELCOME50',
      discountType: 'fixed',
      discountValue: 50,
      minSpend: 400,
      expiryDate: '2027-12-31',
      usageLimit: 500,
      usageCount: 88,
      isActive: true,
    },
    {
      id: 'c-3',
      code: 'RAMADAN15',
      discountType: 'percentage',
      discountValue: 15,
      minSpend: 1500,
      maxDiscount: 500,
      expiryDate: '2027-04-30',
      usageLimit: 300,
      usageCount: 15,
      isActive: true,
    },
  ],
  customers: [
    {
      id: 'cust-1',
      name: 'তানভীর আহমেদ',
      phone: '01712345678',
      email: 'tanveer@gmail.com',
      defaultAddress: 'House 42, Road 9, Mirpur 10, Dhaka',
      defaultDistrict: 'Dhaka',
      defaultDivision: 'Dhaka',
      createdAt: '2026-01-10T10:00:00Z',
      ordersCount: 3,
      totalSpent: 4850,
    },
    {
      id: 'cust-2',
      name: 'মাহমুদুল হাসান',
      phone: '01898765432',
      email: 'mahmud@yahoo.com',
      defaultAddress: 'Flat 4B, Nasirabad Housing, Chittagong',
      defaultDistrict: 'Chittagong',
      defaultDivision: 'Chittagong',
      createdAt: '2026-02-14T11:20:00Z',
      ordersCount: 2,
      totalSpent: 2600,
    },
    {
      id: 'cust-3',
      name: 'সালমা জাহান',
      phone: '01799887766',
      email: 'salma.jahan@gmail.com',
      defaultAddress: 'Sector 4, Road 11, House 29, Uttara, Dhaka',
      defaultDistrict: 'Dhaka',
      defaultDivision: 'Dhaka',
      createdAt: '2026-03-01T09:00:00Z',
      ordersCount: 1,
      totalSpent: 2230,
    },
  ],
  reviews: [
    {
      id: 'rev-1',
      author: 'কাজী মোঃ নাজমুল',
      city: 'উত্তরা, ঢাকা',
      rating: 5,
      comment: 'কাঠের ঘানির সরিষার তেলের ঝাঁঝ এবং স্বাদ অসাধারণ! বাজারের কোনো ব্র্যান্ডের তেলে এমন আসল স্বাদ পাই না। আলহামদুলিল্লাহ, বারাকাহ এগ্রোর সততা অব্যাহত থাকুক।',
      productName: 'কাঠের ঘানিতে ভাঙ্গা খাঁটি সরিষার তেল',
      image: '/images/barakah/customer1.png',
      verified: true,
      date: '১৮ সেপ্টেম্বর ২০২৬',
    },
    {
      id: 'rev-2',
      author: 'ডাঃ রাশেদুল ইসলাম',
      city: 'ধানমন্ডি, ঢাকা',
      rating: 5,
      comment: 'শুকনো সাজনা পাতা নিয়মিত সকালে কুসুম গরম পানিতে খাই। শরীরে ক্লান্তি থাকে না এবং হজম চমৎকার হয়। প্যাকেজিং খুবই পরিচ্ছন্ন ছিল।',
      productName: 'শুকনো সাজনা পাতা / মোরিঙ্গা গুঁড়া',
      image: '/images/barakah/customer2.png',
      verified: true,
      date: '১৫ সেপ্টেম্বর ২০২৬',
    },
    {
      id: 'rev-3',
      author: 'ফারহানা আক্তার',
      city: 'চট্টগ্রাম',
      rating: 5,
      comment: 'সুন্দরবনের মধুর স্বাদ অতুলনীয়। মিষ্টির পাশাপাশি হালকা বুনো সুবাস পাওয়া যায়, যা আসল মধুর বৈশিষ্ট্য। দ্রুত ডেলিভারির জন্য ধন্যবাদ।',
      productName: 'সুন্দরবনের প্রাকৃতিক চাকের মধু',
      image: '/images/barakah/customer3.png',
      verified: true,
      date: '১২ সেপ্টেম্বর ২০২৬',
    },
    {
      id: 'rev-4',
      author: 'মুহাম্মদ মহসিন',
      city: 'মিরপুর, ঢাকা',
      rating: 5,
      comment: 'দেশি গাওয়া ঘি এর ঘ্রাণে পুরো বাড়ি ম-ম করে! ডালে বা গরম ভাতে এক চামচেই খাবারের তৃপ্তি বদলে যায়। বারবার অর্ডার করব ইনশাআল্লাহ।',
      productName: 'খাঁটি গাওয়া ঘি',
      image: '/images/barakah/customer4.png',
      verified: true,
      date: '০৮ সেপ্টেম্বর ২০২৬',
    },
    {
      id: 'rev-5',
      author: 'আহসান হাবীব',
      city: 'সিলেট',
      rating: 5,
      comment: 'পাট পাতার শুকনা পাতা পেয়ে শৈশবের স্মৃতি মনে পড়ে গেল। অসাধারণ ভেষজ গুণাবলি। বারাকাহ এগ্রোর সার্ভিস খুবই পেশাদার।',
      productName: 'শুকনো পাট পাতা গুঁড়া',
      image: '/images/barakah/customer5.png',
      verified: true,
      date: '০১ সেপ্টেম্বর ২০২৬',
    },
  ],
};

function ensureDbExists(): DatabaseSchema {
  if (!fs.existsSync(DATA_DIR)) {
    fs.mkdirSync(DATA_DIR, { recursive: true });
  }

  if (!fs.existsSync(DB_FILE)) {
    fs.writeFileSync(DB_FILE, JSON.stringify(initialSeed, null, 2), 'utf-8');
    return initialSeed;
  }

  try {
    const content = fs.readFileSync(DB_FILE, 'utf-8');
    return JSON.parse(content);
  } catch (err) {
    console.error('Error reading db.json, restoring initial seed:', err);
    fs.writeFileSync(DB_FILE, JSON.stringify(initialSeed, null, 2), 'utf-8');
    return initialSeed;
  }
}

export function getDb(): DatabaseSchema {
  return ensureDbExists();
}

export function saveDb(data: DatabaseSchema): void {
  ensureDbExists();
  fs.writeFileSync(DB_FILE, JSON.stringify(data, null, 2), 'utf-8');
}
